sudocool/urls.py
from django.urls import re_path

from sudocool import views


app_name = "sudocool"
urlpatterns = [
    re_path(r'^([0-9,]+)?$', views.index, name = 'index'),
    re_path(r'^solve/$', views.solve, name = 'solve'),
    re_path(r'^solution/(\d+)$', views.solution, name = 'solution'),
    re_path(r'^puzzle/', views.puzzle, name = 'puzzle'),
]

urls.py
from django.urls import include, re_path
from django.contrib import admin

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^sudocool/', include('sudocool.urls', namespace='sudocool')),
    re_path(r'^', include('sudocool.urls', namespace='sudocool')),
]

sudocool/models.py
from django.db import models

class SudocoolBoardManager(models.Manager):
    def create_sudocoolboard(self, sudocoolData):
        sudocoolBoard = self.create(sudocoolData = sudocoolData)
        sudocoolBoard.save()
        return sudocoolBoard


class SudocoolBoard(models.Model):
    created_date = models.DateTimeField(auto_now_add=True)
    sudocoolData = models.CharField(max_length=161)

    def __unicode__(self):
        return self.sudocoolData

    objects = SudocoolBoardManager()

sudocool/forms.py
from django import forms

class SolveForm(forms.Form):
    sudocoolData = forms.CharField(max_length=161)

class GetPuzzleForm(forms.Form):
    puzzleURL = forms.CharField()

sudocool/views.py
import requests

from django.shortcuts import get_object_or_404, render, redirect

from sudocool.models import SudocoolBoard
from sudocool.forms import SolveForm, GetPuzzleForm
from sudocool.solve.board import Board
from sudocool.solve.solver import BoardSolver

section_size = 3;
num_sections = section_size**2;

def index(request, puzzle = None):
    context = {'range': range(num_sections)}
    if puzzle != None:
        b = Board()
        b.populateByRow(puzzle)
        context['puzzle'] = b.printBySection()
    return render(request, 'sudocool/index.html', context)

def solve(request):
    if request.method == 'POST':
        form = SolveForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            board = SudocoolBoard.objects.create_sudocoolboard(cd['sudocoolData'])
            return redirect('sudocool:solution', board.id)
    return redirect('sudocool:index')

def solution(request, sudocoolboard_id):
    sudocoolboard = get_object_or_404(SudocoolBoard, pk = sudocoolboard_id)

    # generate Board for the given sudocoolboard, and solve it
    b = Board()
    b.populateBySection(sudocoolboard.sudocoolData)
    bs = BoardSolver(b)
    bs.solve()

    # render a response containing the solution
    return render(request, 'sudocool/solution.html', {'range': range(num_sections), 'solution': bs.board.printBySection()})

def puzzle(request):
    if request.method == 'POST':
        form = GetPuzzleForm(request.POST)
        if not form.is_valid():
            form.cleaned_data["puzzleURL"] = "http://sudoku.com.au"
        try:
            html = requests.get(form.cleaned_data["puzzleURL"]).text
            index = html.find("var iGridUnsolved= new Array(")+len("var iGridUnsolved= new Array(")
            array = html[index:index+161]
            return redirect('sudocool:index', array)
        except (ValueError):
            return redirect('sudocool:index')
    return redirect('sudocool:index')

sudocool/templates/sudocool/_sudocooltable.html
<div class="sudocool-table-wrapper">
    <div class="sudocool-table">
        {% for section in range %}
            <div class="sudocool-section">
                {% for item in range %}
                    <input class="sudocool-item"/>
                {% endfor %}
            </div>
        {% endfor %}
    </div>
</div>

sudocool/templates/sudocool/index.html
{% extends "SudoCool/base.html" %}

{% block content %}
    <form id="getSudokuForm" action="{% url 'sudocool:puzzle' %}" method="post">
        {% csrf_token %}
        <input id="puzzleURL" name="puzzleURL" type="text" placeholder="Enter sudoku.com.au URL to get puzzle"/>
        <input type="submit" value="Get" class="button"/>
    </form>
    <form id="solveSudocoolForm" action="{% url 'sudocool:solve' %}" method="post">
        <input type="hidden" id="puzzleString" value="{{ puzzle }}"/>
        <div class="sudocool-container">
            {% include "sudocool/_sudocooltable.html" %}
            {% csrf_token %}
            <input type="submit" value="Solve" class="button"/>
        </div>
    </form>
{% endblock %}

sudocool/templates/sudocool/solution.html
{% extends "SudoCool/base.html" %}

{% block content %}
    <div class="row">
        <div class="large-12 columns">
            <div class="sudocool-container">
                <input type="hidden" id="solutionString" value="{{ solution }}"/>
                {% include "sudocool/_sudocooltable.html" %}
                <a href="{% url 'sudocool:index' %}" class="button">Back</a>
            </div>
        </div>
    </div>
{% endblock %}

templates/SudoCool/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>SudoCool</title>
        <link rel="stylesheet" type="text/css" href="/static/css/application.css" />
    </head>
    <body>

        <nav class="title">
            <h1><a href="{% url 'sudocool:index' %}">SudoCool</a></h1>
        </nav>

        <div class="content">
            {% block content %}{% endblock %}
        </div>

        <script src="/static/js/jquery-3.5.1.slim.min.js"></script>
        <script src="/static/js/application.js"></script>
    </body>
</html>